#设置项目启动名称及eureka客户端
#数据微服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: data-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8
    username: root
    password: admin
