#视图微服feign(ribbon的封装，面向接口式服务调用）
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: html5
  mvc:
    static-path-pattern: /**

feign.hystrix.enabled: true
